mantisbt:
  image: vimagick/mantisbt:latest
  ports:
    - "8959:80"
  links:
    - mysql
  restart: unless-stopped

mysql:
  image: mysql:5.7
  volumes:
    - ./data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  restart: unless-stopped
