version: "3"
networks:
  default:
    name: databases
    external: true
services:
  redis:
    image: bitnami/redis
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    #Volume must habe UID 1001
    environment:
      - TZ=America/Caracas
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - "./data:/bitnami/"
