version: '3'
networks:
  default:
    name: frontend
    external: true
services:
  anse-demo:
    image: ddiu8081/anse:latest
    container_name: anse
    restart: unless-stopped
    ports:
      - '8267:3000'
