version: '3'
networks:
  default:
    name: frontend
    external: true
services:
  draw:
    image: jgraph/drawio
    container_name: drawio
    ports:
      - 8387:8080
      # - 8443:8443
    restart: 'unless-stopped'
