version: '3.7'

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    # build:
    #   context: .
    ports:
      - 7095:80
    volumes:
      - ./akaunting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - AKAUNTING_SETUP=true
    depends_on:
      - akaunting-db

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - ./akaunting-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - db.env

volumes:
  akaunting-data:
  akaunting-db:
