version: "3.9"
services:
  obsidian:
    image: ghcr.io/sytone/obsidian-remote:latest
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8040:8080
    volumes:
      - ./vault:/vaults
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      # - CUSTOM_USER=${USER}
      # - PASSWORD=${PASS}
      - TITLE=Obsidian
      - KEYBOARD=es-es-qwerty
      # - DOCKER_MODS=linuxserver/mods:universal-git
