theme = "monokai_pro_spectrum" 

[editor]
true-color = true
mouse = true
scroll-lines = 3
line-number = "relative"
auto-completion = true
auto-format = true
auto-info = true
bufferline = "always"
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["workspace-diagnostics", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "underline"
normal = "bar"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.characters]
space = "-"
nbsp = "⍽"
tab = "→"
newline = " "
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "|"

[keys.normal.space]
q = ":quit"
w = [":w",":config-reload"]