version: "3.8"
services:
  openrefine:
    image: vimagick/openrefine
    container_name: openrefine
    ports:
      - "3333:3333"
    volumes:
      - ./data:/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
