version: '3'
networks:
  default:
    name: frontend
    external: true
services:
  bytebase:
    image: bytebase/bytebase:2.13.2
    container_name: bytebase
    restart: unless-stopped
    healthcheck:
      disable: true
    volumes:
      - ./data:/var/opt/bytebase
    ports:
      - ${BB_PORTS}
    command: --data /var/opt/bytebase --pg ${BB_PG} --external-url ${BB_EXTERNAL_URL} --port 8080 --disable-sample --disable-metric
