---
version: "2"
networks:
  default:
    name: backend
    external: true
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:jackett
    volumes:
      - ./config:/config
      - ${JKT_OUTPUT}
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - "8191:8191"
    restart: unless-stopped
