---
version: "2"
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Caracas
      - UMASK_SET=022
    volumes:
      - /:/host:ro,rslave
    ports:
      - 9100:9090
    restart: unless-stopped
