version: '3'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ACCESS_CODE=${ACCESS_CODE}
    ports:
      - "3210:3210"
