version: "3"
networks:
  default:
    name: backend
    external: true
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    environment:
      - PUID=1000
      - PGID=1000
      # - DARK_MODE=1
    ports:
      - 5800:5800
    volumes:
      - ./data:/config:rw
      - ${JD2_OUTPUT}
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
