version: '3.8'
services:
  kasmweb:
    image: kasmweb/chrome:1.14.0
    container_name: chromekasm
    ports:
      - 6901:6901
    environment:
      - VNC_PW=${VNC_PW}
    shm_size: 512m
    restart: unless-stopped
