version: "2.1"
services:
  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - MAXMEM=1024
    volumes:
      - ./config:/config
      - ./books:/books
      - ./comics:/comics
      - ./files:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
