version: '3.7'
services:
  osticket-app:
    image: tiredofit/osticket
    container_name: osticket-app
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.osticket-app.rule=Host(`osticket.example.com`)
    #   - traefik.http.services.osticket-app.loadbalancer.server.port=8034
    ports:
      - "8034:80"
    volumes:
      - ./data/:/www/osticket
      - ./logs/:/www/logs
    environment:
      - TIMEZONE=${TIMEZONE}
      - CONTAINER_NAME=${CONTAINER_NAME_APP}

      - CRON_INTERVAL=${CRON_INTERVAL}

      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}

      - INSTALL_SECRET=${INSTALL_SECRET}
      - INSTALL_EMAIL=${INSTALL_EMAIL}
      - INSTALL_NAME=${INSTALL_NAME}

      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
    # networks:
      # - proxy
      # - services
    restart: unless-stopped

  osticket-db:
    image: tiredofit/mariadb:10.11
    container_name: osticket-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TIMEZONE=${TIMEZONE}
      - CONTAINER_NAME=${CONTAINER_NAME_DB}

      - ROOT_PASS=${ROOT_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    # networks:
    #   - services
    restart: unless-stopped

  osticket-db-backup:
    container_name: osticket-db-backup
    image: tiredofit/db-backup:latest
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=${TIMEZONE}
      - CONTAINER_NAME=${CONTAINER_NAME_DB_BKP}
      - DB_HOST=${DB_HOST}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DUMP_FREQ=${DB_DUMP_FREQ}
      - DB_DUMP_BEGIN=${DB_DUMP_BEGIN}
      - DB_CLEANUP_TIME=${DB_CLEANUP_TIME}
    # networks:
    #   - services
    restart: unless-stopped

# networks:
  # proxy:
  #   external: true
  # services:
    # external: true

