version: "3.9"
networks:
  default:
    name: frontend
    external: true
services:
  excalidraw:
    container_name: excalidraw
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    image: excalidraw/excalidraw:latest
    ports:
      - 5000:80
    restart: unless-stopped
    stdin_open: true
    environment:
      - NODE_ENV=production
