version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${WIRE_PUID}
      - PGID=${WIRE_PGID}
      - TZ=${WIRE_TZ}
      - SERVERURL=${WIRE_SERVER_URL}
      - SERVERPORT=${WIRE_SERVER_PORT}
      - PEERS=${WIRE_PEERS}
      - PEERSDNS=${WIRE_PEERS_DNS}
      #- INTERNAL_SUBNET=
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    dns:
      - ${WIRE_PEERS_DNS}
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
