services:
  wordpress:
    image: wordpress:latest
    ports:
      - 7957:80
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - ./data:/var/www/html
networks:
  default:
    name: frontend
    external: true
