version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
    volumes:
      - ./config:/config
      - ${DO_PATH}:/downloads
      - ${TV_PATH}:/sync/tv
      - ${MOV_PATH}:/sync/movies
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
