---
version: "2"
networks:
  default:
    name: backend
    external: true
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - UMASK_SET=022
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
    volumes:
      - ./config:/config
      - ${SONRR_TV}
      - ${SONRR_OUTPUT}
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
