---
version: "2"
networks:
  default:
    name: backend
    external: true
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - UMASK_SET=022 #optional
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
    volumes:
      - ./config:/config
      - ${RADRR_MOVIES}
      - ${RADRR_OUTPUT}
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
