version: '3'
services:
  sqlchat:
    image: sqlchat/sqlchat
    container_name: sqlchat
    platform: linux/amd64
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - OPENAI_API_ENDPOINT=${OPENAI_API_ENDPOINT}
      # - DATABASE_URL=${DATABASE_URL}
      # - NEXT_PUBLIC_DATABASE_LESS=${NEXT_PUBLIC_DATABASE_LESS}
    ports:
      - 5679:3000
