version: '3'
networks:
  default:
    name: backend
    external: true
services:
  weblate:
    image: weblate/weblate
    volumes:
      - ./weblate-data:/app/data
      - ./weblate-cache:/app/cache
    env_file:
      - ./.env
    ports:
      - 8070:8080
    restart: unless-stopped
    depends_on:
      # - database
      - cache
  # database:
  #   image: postgres:15-alpine
  #   env_file:
  #   - ./.env
  #   volumes:
  #   - ./postgres-data:/var/lib/postgresql/data
  #   restart: always
  cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: [ redis-server, --save, '60', '1' ]
    volumes:
      - ./redis-data:/data
