version: "3"
networks:
  default:
    name: backend
    external: true
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - ${QBIT_OUTPUT}
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
