version: "3"
networks:
  default:
    name: databases
    external: true
services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    # image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASS}
      - TZ=America/Caracas
      - MSSQL_PID=Express
    hostname: mssqlserver
    user: root
    #When using volumes is best to set user root cause microsoft doesn't know how to properly set PID and GID...
    volumes:
      - ./data:/var/opt/mssql
    restart: unless-stopped
