version: "3"
networks:
  default:
    name: frontend
    external: true
services:
  web:
    image: yidadaa/chatgpt-next-web
    ports:
      - "8267:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_KEY}
      - CODE=${PASSWORD}
    restart: unless-stopped
