version: "3"
services:
  web:
    image: yidadaa/chatgpt-next-web
    ports:
      - "8200:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_KEY}
      - CODE=${PASSWORD}
    restart: unless-stopped
